"""fix acty relation

Revision ID: cc8d1590d062
Revises: f7805b9dff10
Create Date: 2025-08-07 15:48:41.048859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8d1590d062'
down_revision: Union[str, Sequence[str], None] = 'f7805b9dff10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_activities_organization_id_fkey'), 'organization_activities', type_='foreignkey')
    op.drop_constraint(op.f('organization_activities_activity_id_fkey'), 'organization_activities', type_='foreignkey')
    op.create_foreign_key(None, 'organization_activities', 'economic_activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_activities', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organization_activities', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_activities', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'organization_activities', type_='foreignkey')
    op.drop_constraint(None, 'organization_activities', type_='foreignkey')
    op.create_foreign_key(op.f('organization_activities_activity_id_fkey'), 'organization_activities', 'economic_activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('organization_activities_organization_id_fkey'), 'organization_activities', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
